# .github/workflows/main.yml

name: Build Angular App # Nome do seu workflow

on:
  push:
    branches:
      - main # O workflow será disparado sempre que houver um push para a branch 'main'
  pull_request:
    branches:
      - main # O workflow também será disparado em pull requests para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest # O ambiente de execução do job (máquina virtual Linux)

    steps:
      - name: Checkout Repository # Passo para clonar o seu repositório GitHub
        uses: actions/checkout@v4

      - name: Set up Node.js # Passo para configurar o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a versão do Node.js que seu projeto Angular suporta (Angular 18 geralmente usa Node 18+)

      - name: Install Dependencies # Instala as dependências do projeto Angular
        run: npm ci # 'npm ci' é recomendado em ambientes de CI/CD para builds limpos e consistentes

      - name: Build Angular Application # Constrói o aplicativo Angular
        run: npm run build -- --configuration=production # Executa o comando de build do Angular para produção
        # Se você tiver um base href diferente para o GitHub Pages, pode adicionar --base-href /<repo-name>/
        # Exemplo: npm run build -- --configuration=production --base-href /fear-idle-game/
        # O '--' é importante para passar flags adicionais para o comando ng build

      - name: Archive Production Build # Opcional: Salva os arquivos de build como um artefato do workflow
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/ # Onde o Angular gera os arquivos de build (geralmente 'dist/' ou 'dist/<project-name>')
